# Generated by Django 5.2.4 on 2025-07-24 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pago",
            name="monto",
            field=models.DecimalField(
                decimal_places=2, help_text="Monto total a pagar", max_digits=8
            ),
        ),
        migrations.CreateModel(
            name="PagoParcial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=8)),
                ("fecha", models.DateField(auto_now_add=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_parciales",
                        to="pagos.pago",
                    ),
                ),
            ],
        ),
    ]
