# Generated by Django 5.2.4 on 2025-07-22 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='duracion_semanas',
        ),
    ]
