# Generated by Django 5.2.4 on 2025-07-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_curso_duracion_semanas'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio del curso', max_digits=8),
        ),
    ]
