# Generated by Django 5.2.4 on 2025-07-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0004_alter_curso_profesor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="profesor",
        ),
        migrations.AlterField(
            model_name="curso",
            name="instrumento",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
