# Generated by Django 5.2.4 on 2025-07-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del aula (ej: Aula 101)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "sede",
                    models.CharField(
                        choices=[("MATRIZ", "Sede Matriz"), ("NORTE", "Sede Norte")],
                        default="MATRIZ",
                        max_length=10,
                    ),
                ),
                (
                    "edificio",
                    models.CharField(
                        choices=[
                            ("NUEVO", "Edificio Nuevo"),
                            ("VIEJO", "Edificio Viejo"),
                        ],
                        default="NUEVO",
                        max_length=10,
                    ),
                ),
                (
                    "piso",
                    models.CharField(
                        choices=[("1", "Piso 1"), ("2", "Piso 2"), ("3", "Piso 3")],
                        default="1",
                        max_length=2,
                    ),
                ),
                (
                    "capacidad",
                    models.PositiveIntegerField(
                        default=15, help_text="Capacidad máxima de estudiantes"
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el aula está disponible para uso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
                "ordering": ["sede", "edificio", "piso", "nombre"],
            },
        ),
    ]
