# Generated by Django 5.2.4 on 2025-07-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_curso_profesor'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
