# Generated by Django 5.2.4 on 2025-07-24 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cursos", "0004_alter_curso_profesor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("descripcion", models.TextField(blank=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clases",
                        to="cursos.curso",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"rol": "PROFESOR"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clases_profesor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
