# Generated by Django 5.2.4 on 2025-07-24 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aulas", "0001_initial"),
        ("horarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="horario",
            name="aula",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clases_aula",
                to="aulas.aula",
            ),
        ),
    ]
