# Generated by Django 5.2.4 on 2025-07-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='fecha',
            new_name='fecha_fin',
        ),
        migrations.AddField(
            model_name='horario',
            name='fecha_inicio',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
