# Generated by Django 5.2.4 on 2025-07-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horarios", "0002_horario_aula"),
    ]

    operations = [
        migrations.AddField(
            model_name="horario",
            name="cupos",
            field=models.PositiveIntegerField(
                default=15, help_text="Cupos máximos para la clase"
            ),
        ),
    ]
