# Generated by Django 5.2.4 on 2025-07-24 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aulas", "0001_initial"),
        ("horarios", "0002_rename_fecha_horario_fecha_fin_horario_fecha_inicio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="horario",
            name="aula",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clases_aula",
                to="aulas.aula",
            ),
        ),
        migrations.AlterField(
            model_name="horario",
            name="profesor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"rol": "PROFESOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clases_profesor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
