# Generated by Django 5.2.4 on 2025-07-24 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("horarios", "0003_alter_horario_aula_alter_horario_profesor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="horario",
            name="aula",
        ),
    ]
