# Generated by Django 5.2.4 on 2025-07-23 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horarios', '0002_rename_fecha_horario_fecha_fin_horario_fecha_inicio'),
        ('matriculas', '0002_alter_matricula_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('TARDE', 'Llegó tarde'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Ausencia justificada')], default='AUSENTE', max_length=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='horarios.horario')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='matriculas.matricula')),
            ],
            options={
                'ordering': ['-fecha', 'matricula__estudiante__first_name'],
                'unique_together': {('matricula', 'fecha')},
            },
        ),
    ]
