# Generated by Django 5.2.4 on 2025-07-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PRESENTE", "Presente"),
                            ("TARDE", "Llegó tarde"),
                            ("AUSENTE", "Ausente"),
                            ("JUSTIFICADO", "Ausencia justificada"),
                        ],
                        default="AUSENTE",
                        max_length=12,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-fecha", "matricula__estudiante__first_name"],
            },
        ),
    ]
