# Generated by Django 5.2.4 on 2025-07-24 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("asistencias", "0001_initial"),
        ("horarios", "0001_initial"),
        ("matriculas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asistencia",
            name="clase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asistencias",
                to="horarios.horario",
            ),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="matricula",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asistencias",
                to="matriculas.matricula",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asistencia",
            unique_together={("matricula", "fecha")},
        ),
    ]
